### ISSUE TITLE
Chart lines doesn't show up in Safari on macOS

### ISSUE THREAD

**Issue by eproxus** [timqian/chart.xkcd#3] opened 2019-08-19 12:22 UTC
Charts on https://timqian.com/chart.xkcd/ or on CodePen doesn't have any lines. The only working chart is the donut chart.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/112878/63264967-b4709d80-c28c-11e9-9988-3018e7f36279.png">

**Comment by iamacarpet** [comment] 2019-08-19 14:08
Ditto on iOS from an iPhone

Love the library though, it looks pretty sweet!

**Comment by dongm2ez** [comment] 2019-08-20 03:03
I found in Safari `filter="url(#xkcdify-pie)"` is ok, but `filter="url(#xkcdify)"` is no display chart

**Comment by timqian** [comment] 2019-08-26 15:07
seems a performance issue on safri, this issue is fixed in 0a6498a and released in v1.0.9.

Have not figured out the root cause, will keep this issue open for a while

**Closed** 2019-08-27 01:10 UTC
